### ISSUE TITLE
Very cool!

### ISSUE THREAD

**Issue by tin2tin** [CoolAracan/BlenderVideoSequenceTools#1]
Very cool set of functions in your add-on. I just tweeted about it. If you have a continued interest in the VSE, come and hang out in the VSE chat: https://blender.chat/channel/vse

**Comment by CoolAracan** [comment]
Hi tin2tin,
thanks for the kind words and the tweet! :) 
I will definitely check out the chat sometimes. Didn't know blender.chat existed up until now.
